# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/felipe_xavier/Projects/NeuralNetcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/felipe_xavier/Projects/NeuralNetcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/felipe_xavier/Projects/NeuralNetcpp/CMakeFiles /home/felipe_xavier/Projects/NeuralNetcpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/felipe_xavier/Projects/NeuralNetcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neuralnet.out

# Build rule for target.
neuralnet.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 neuralnet.out
.PHONY : neuralnet.out

# fast build rule for target.
neuralnet.out/fast:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/build
.PHONY : neuralnet.out/fast

Main.o: Main.cpp.o

.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/Main.cpp.s
.PHONY : Main.cpp.s

sources/Matrix.o: sources/Matrix.cpp.o

.PHONY : sources/Matrix.o

# target to build an object file
sources/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/sources/Matrix.cpp.o
.PHONY : sources/Matrix.cpp.o

sources/Matrix.i: sources/Matrix.cpp.i

.PHONY : sources/Matrix.i

# target to preprocess a source file
sources/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/sources/Matrix.cpp.i
.PHONY : sources/Matrix.cpp.i

sources/Matrix.s: sources/Matrix.cpp.s

.PHONY : sources/Matrix.s

# target to generate assembly for a file
sources/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/sources/Matrix.cpp.s
.PHONY : sources/Matrix.cpp.s

sources/NeuralNet.o: sources/NeuralNet.cpp.o

.PHONY : sources/NeuralNet.o

# target to build an object file
sources/NeuralNet.cpp.o:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/sources/NeuralNet.cpp.o
.PHONY : sources/NeuralNet.cpp.o

sources/NeuralNet.i: sources/NeuralNet.cpp.i

.PHONY : sources/NeuralNet.i

# target to preprocess a source file
sources/NeuralNet.cpp.i:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/sources/NeuralNet.cpp.i
.PHONY : sources/NeuralNet.cpp.i

sources/NeuralNet.s: sources/NeuralNet.cpp.s

.PHONY : sources/NeuralNet.s

# target to generate assembly for a file
sources/NeuralNet.cpp.s:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/sources/NeuralNet.cpp.s
.PHONY : sources/NeuralNet.cpp.s

sources/Neuron.o: sources/Neuron.cpp.o

.PHONY : sources/Neuron.o

# target to build an object file
sources/Neuron.cpp.o:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/sources/Neuron.cpp.o
.PHONY : sources/Neuron.cpp.o

sources/Neuron.i: sources/Neuron.cpp.i

.PHONY : sources/Neuron.i

# target to preprocess a source file
sources/Neuron.cpp.i:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/sources/Neuron.cpp.i
.PHONY : sources/Neuron.cpp.i

sources/Neuron.s: sources/Neuron.cpp.s

.PHONY : sources/Neuron.s

# target to generate assembly for a file
sources/Neuron.cpp.s:
	$(MAKE) -f CMakeFiles/neuralnet.out.dir/build.make CMakeFiles/neuralnet.out.dir/sources/Neuron.cpp.s
.PHONY : sources/Neuron.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... neuralnet.out"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... sources/Matrix.o"
	@echo "... sources/Matrix.i"
	@echo "... sources/Matrix.s"
	@echo "... sources/NeuralNet.o"
	@echo "... sources/NeuralNet.i"
	@echo "... sources/NeuralNet.s"
	@echo "... sources/Neuron.o"
	@echo "... sources/Neuron.i"
	@echo "... sources/Neuron.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

